# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f2fe36af0b0b43d79c3de49ac96c176571aed0324d53b1f27ee6d91c5e39e49273df56cd63f3bc3c84453ef18fc35101c3d053ce7707eb54890bd712791ad6e1

test:
  secret_key_base: 267d2c09f358b3af32b68fa398b044ca339051f10d81ed5d7e47cb6edd465b772a6ccb1c08d4b3fb5d6e57d7bbebd995c01c090a0013a11e4e6c675d8b1f82b3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
